### ISSUE TITLE
Blogs: Banner styling not saving

### ISSUE THREAD

**Issue by HunterSchindo-CU** [CornellCustomDev/cwd_base_wp#30]
Changes made to the header using the customizer don't necessarily work as expected. Saving the changes has no impact - as seen on this site: 

[https://blogs.cornell.edu/susanbuckmorss/](https://blogs.cornell.edu/susanbuckmorss/)

Customizer link: https://blogs.cornell.edu/susanbuckmorss/wp-admin/customize.php?url=https%3A%2F%2Fblogs.cornell.edu%2Fsusanbuckmorss%2F

Resaving theme options doesn't address the issue.

**Comment by dc774** [comment]
This is working now. Changing and saving customizer changes in the Banner and Academic Unit tabs seems to have fixed it.
