### ISSUE TITLE
Homepage set to blog -> no titles + no post separation

### ISSUE THREAD

**Issue by HunterSchindo-CU** [CornellCustomDev/cwd_base_wp#33]
Reading Settings:

- Your Homepage Displays: Your latest posts

This results in posts merged together with no separation or blog titles. A template is needed for this configuration.

Please contact David Silbey when resolved - ticket submitted: https://tdx.cornell.edu/TDNext/Apps/32/Tickets/TicketDet.aspx?TicketID=1464109

**Comment by dc774** [comment]
Looks like you got the theme activated. Thanks! I'll start paying more attention to these issues via GitHub notifications.
