### ISSUE TITLE
Blogs: Posts have Cornell Seal image added to content

### ISSUE THREAD

**Issue by HunterSchindo-CU** [CornellCustomDev/cwd_base_wp#34]
This is inconsistent in my testing and may depend on when a site was created that uses the theme, but it's happened on a few sites I've worked on with Chuck. Here's an example: 

https://blogs.cornell.edu/susanbuckmorss/uncategorized/test/

**Comment by dc774** [comment]
Yeah, I just tested it locally with this repo and it looks like it's not an issue here. Closing it.
