### ISSUE TITLE
Periods missing from excerpts

### ISSUE THREAD

**Issue by HunterSchindo-CU** [CornellCustomDev/cwd_base_wp#35]
Autogenerated excerpts have periods removed - example: https://blogs.cornell.edu/onehealth/public-health-news/

December 2, 2024's entry: 2024 Public Health Magazine

Original text: 

> Our Master’s Program publishes an annual magazine to provide students, alumni, prospective students, donors, advisors, and friends with a beautiful annual summary of our work.
> 
> In this year’s magazine we focus on engagement. To have the greatest impacts, we must reach beyond classroom walls to work directly with communities and organizations in New York and around the world.

Excerpt displayed: 

> Our Master’s Program publishes an annual magazine to provide students, alumni, prospective students, donors, advisors, and friends with a beautiful annual summary of our work In this year’s magazine we focus on engagement To have the greatest impacts, we must...

**Comment by HunterSchindo-CU** [comment]
I've advised the site owner to use manual excerpt sections - so if the example has been corrected, please check to see if the manual excerpt section has been utilized.

**Comment by dc774** [comment]
This is fixed. Note: The excerpt function in our theme only applies to the classic editor. We may have to decide how to handle excerpts in the new block theme.
